spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${{ DATASOURCE_URL }}
    username: ${{ DATASOURCE_USERNAME }}
    password: ${{ DATASOURCE_PASSWORD }}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: smtp.gmail.com
    port: 587
    username: yujinkwon.dev@gmail.com
    password: ${{ GOOGLE_EMAIL_APP_PASSWORD }}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2
          auth: true
        transport:
          protocol: smtp
        debug: true



  redis:
    host: ${{ REDIS_HOST }}
    port: ${{ REDIS_PORT }}

jwt:
  header: Authorization
  secret: ${{ JWT_SECRET }}
  expire-time:
    access-token: 31536000000 #1년, 테스트용
    refresh-token: 604800000 #7일

cloud:
  aws:
    s3:
      bucket: ${{ AWS_S3_BUCKET_NAME }}
    credentials:
      access-key: ${{ AWS_S3_ACCESS_KEY }}
      secret-key: ${{ AWS_S3_SECRET_KEY }}
    region:
      auto: false
      static: ${{ AWS_S3_REGION }}
    stack:
      auto: false

cipher:
  type: ${{ CIPHER_TYPE }}
  mode: ${{ CIPHER_MODE }}

hash:
  type: ${{ HASH_TYPE }}
  mode: ${{ HASH_MODE }}