
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${{ DATASOURCE_URL }}
    username: ${{ DATASOURCE_USERNAME }}
    password: ${{ DATASOURCE_PASSWORD }}

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  cloud:
    aws:
      s3:
        bucket: ${{ AWS_S3_BUCKET_NAME }}
      credentials:
        access-key: ${{ AWS_S3_ACCESS_KEY }}
        secret-key: ${{ AWS_S3_SECRET_KEY }}
      region:
        static: ${{ AWS_S3_REGION }}
      stack:
        auto: false

