name: catchat server CI/CD

on:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    name: CI PipeLine
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set project from github secret
      uses: microsoft/variable-substitution@v1
      with:
        files: ./src/main/resources/application.yml
      env:
        spring.datasource.url: ${{ secrets.DATASOURCE_URL }}
        spring.datasource.username: ${{ secrets.DATASOURCE_USERNAME }}
        spring.datasource.password: ${{ secrets.DATASOURCE_PASSWORD }}
        spring.cloud.aws.s3.bucket: ${{ secrets.AWS_S3_BUCKET_NAME }}
        spring.cloud.aws.credentials.access-key: ${{ secrets.AWS_S3_ACCESS_KEY }}
        spring.cloud.aws.credentials.secret-key: ${{ secrets.AWS_S3_SECRET_KEY }}
        spring.cloud.aws.region.static: ${{ secrets.AWS_S3_REGION }}

    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build
      shell: bash