name: catchat server CI/CD

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: CI_CD PipeLine
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set project from github secret
      uses: microsoft/variable-substitution@v1
      with:
        files: ./src/main/resources/application.yml
      env:
        spring.datasource.url: ${{ secrets.DATASOURCE_URL }}
        spring.datasource.username: ${{ secrets.DATASOURCE_USERNAME }}
        spring.datasource.password: ${{ secrets.DATASOURCE_PASSWORD }}
        cloud.aws.s3.bucket: ${{ secrets.AWS_S3_BUCKET_NAME }}
        cloud.aws.credentials.access-key: ${{ secrets.AWS_S3_ACCESS_KEY }}
        cloud.aws.credentials.secret-key: ${{ secrets.AWS_S3_SECRET_KEY }}
        cloud.aws.region.static: ${{ secrets.AWS_S3_REGION }}
        jwt.secret: ${{ secrets.JWT_SECRET }}
        spring.mail.password: ${{ secrets.GOOGLE_EMAIL_APP_PASSWORD }}

    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew clean build
      shell: bash

    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DDTHH-mm-ss
        utcOffset: "+09:00"

    - name: Generate deployment package
      run: |
        mkdir -p deploy
        cp build/libs/*.jar deploy/application.jar
        cp Procfile deploy/Procfile
        cp -r .ebextensions deploy/.ebextensions
        cp -r .platform deploy/.platform
        cd deploy && zip -r deploy.zip .

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_EB_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_EB_SECRET_KEY }}
        region: ${{ secrets.AWS_EB_REGION }}
        application_name: ${{ secrets.AWS_EB_APPLICATION_NAME }}
        environment_name: ${{ secrets.AWS_EB_ENVIRONMENT_NAME }}
        version_label: catchat-${{ steps.current-time.outputs.formattedTime }}
        deployment_package: deploy/deploy.zip
        wait_for_environment_recovery: 300